# -*- coding: utf-8 -*-
"""Phân_tích_marketing_UPDATED.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14eunN1vcloYJmHAluoZzuqaFCIcFxbWE
"""

# ============================================================
# 0. IMPORT THƯ VIỆN VÀ ĐỌC DỮ LIỆU
# ============================================================

import pandas as pd
import numpy as np

df = pd.read_csv("onlinebuy.csv")  # đổi đường dẫn nếu chạy Colab

print("Kích thước dữ liệu:", df.shape)
df.head()

# ============================================================
# 1. MÔ TẢ DỮ LIỆU (DESCRIPTIVE STATISTICS)
# ============================================================

# Nhóm biến Likert (1–5)
likert_vars = [
    'int1','int2','inf1','inf2','inf3','ve1','ve2','ve3','nvse1','nvse2',
    'trust1','trust2','trust3','conv1','conv2','conv3','conv4',
    'enj1','enj2','enj3','sc1','sc2','al1','al2','al3'
]

desc = df[likert_vars].describe().T
display(desc[['mean','std','min','25%','50%','75%','max']])

print("\nPhân bố giới tính:")
print(df[['gender_0','gender_1']].sum())

print("\nPhân bố nhóm tuổi:")
print(df[['age_0','age_1','age_2']].sum())

print("\nPhân bố tần suất mua sắm:")
print(df[['freq_0','freq_1','freq_2','freq_3']].sum())

# ============================================================
# CELL 1: DATA CLEANING
# ============================================================

print("="*80)
print("🧹 BƯỚC 1: DATA CLEANING")
print("="*80)

# Danh sách các cột Likert cần kiểm tra
likert_cols = [
    'int1','int2','inf1','inf2','inf3','ve1','ve2','ve3','nvse1','nvse2',
    'trust1','trust2','trust3','conv1','conv2','conv3','conv4',
    'enj1','enj2','enj3','sc1','sc2','al1','al2','al3'
]

def check_invalid(row):
    """
    Kiểm tra dữ liệu không hợp lệ:
    1. Tất cả giá trị giống nhau
    2. ≥10 giá trị liên tiếp giống nhau
    """
    vals = row[likert_cols].values

    # Kiểm tra tất cả giống nhau
    if len(set(vals)) == 1:
        return True

    # Kiểm tra 10 liên tiếp giống nhau
    max_c = current = 1
    for i in range(1, len(vals)):
        if vals[i] == vals[i-1]:
            current += 1
            max_c = max(max_c, current)
        else:
            current = 1
    return max_c >= 10

# Tìm và loại bỏ dữ liệu không hợp lệ
print(f"\n🔍 Kiểm tra dữ liệu...")
invalid = [i for i, row in df.iterrows() if check_invalid(row)]

print(f"\n📊 KẾT QUẢ:")
print(f"   Tổng mẫu ban đầu: {len(df)}")
print(f"   Mẫu không hợp lệ: {len(invalid)} ({len(invalid)/len(df)*100:.1f}%)")

if len(invalid) > 0:
    print(f"\n   Ví dụ 5 mẫu đầu tiên bị loại: {invalid[:5]}")

# Loại bỏ
df = df.drop(invalid).reset_index(drop=True)

print(f"\n✅ SAU KHI LÀM SẠCH:")
print(f"   Còn lại: {len(df)} mẫu ({len(df)/(len(df)+len(invalid))*100:.1f}%)")
print(f"   Đã loại: {len(invalid)} mẫu")

# Lưu dữ liệu sạch
df.to_csv('onlinebuy_cleaned.csv', index=False)
print(f"\n💾 Đã lưu: onlinebuy_cleaned.csv")

# ============================================================
# 2. FACTOR ANALYSIS
# ============================================================

print("\n📊 BƯỚC 2: FACTOR ANALYSIS")

# Cài thư viện
!pip install factor-analyzer -q

from factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_kmo, calculate_bartlett_sphericity

# KMO
kmo_all, kmo_model = calculate_kmo(df[likert_cols])
print(f"\nKMO Score: {kmo_model:.3f}")

# Bartlett's
chi2, pval = calculate_bartlett_sphericity(df[likert_cols])
print(f"Bartlett's p-value: {pval:.4f}")

# Determine optimal factors
fa_test = FactorAnalyzer(n_factors=25, rotation=None)
fa_test.fit(df[likert_cols])
ev, v = fa_test.get_eigenvalues()
n_factors = sum(ev > 1.0)
print(f"\nSố nhân tố tối ưu: {n_factors}")

# Run FA
fa = FactorAnalyzer(n_factors=n_factors, rotation='varimax')
fa.fit(df[likert_cols])
loadings_df = pd.DataFrame(
    fa.loadings_,
    index=likert_cols,
    columns=[f'Factor{i+1}' for i in range(n_factors)]
)

print("\nFactor Loadings (|loading| ≥ 0.4):")
for col in loadings_df.columns:
    high = loadings_df[col][abs(loadings_df[col]) >= 0.4].sort_values(ascending=False)
    if len(high) > 0:
        print(f"\n{col}:")
        for var, val in high.items():
            print(f"  {var}: {val:.3f}")

# ============================================================
# TẠO CÁC BIẾN AGGREGATE - CHẠY CELL NÀY TRƯỚC REGRESSION!
# ============================================================

print("🔧 Tạo các biến aggregate...")

# Platform Characteristics
df['INT'] = df[['int1','int2']].mean(axis=1)
df['INF'] = df[['inf1','inf2','inf3']].mean(axis=1)
df['VE'] = df[['ve1','ve2','ve3']].mean(axis=1)
df['NVSE'] = df[['nvse1','nvse2']].mean(axis=1)

# Psychological Responses
df['TRUST'] = df[['trust1','trust2','trust3']].mean(axis=1)
df['CONV'] = df[['conv1','conv2','conv3','conv4']].mean(axis=1)
df['ENJ'] = df[['enj1','enj2','enj3']].mean(axis=1)
df['SC'] = df[['sc1','sc2']].mean(axis=1)

# Attitudinal Loyalty
df['AL'] = df[['al1','al2','al3']].mean(axis=1)

print("✅ XONG! Đã tạo 9 biến: INT, INF, VE, NVSE, TRUST, CONV, ENJ, SC, AL")
print(f"\n📊 Thống kê:")
print(df[['INT', 'INF', 'VE', 'NVSE', 'TRUST', 'CONV', 'ENJ', 'SC', 'AL']].describe().T[['mean','std']].round(3))

# ============================================================
# 3. REGRESSION
# ============================================================

print("\n📈 BƯỚC 3: REGRESSION ANALYSIS")

import statsmodels.api as sm

# Tạo biến
df['AL'] = df[['al1','al2','al3']].mean(axis=1)

# Regression 1
X1 = sm.add_constant(df[['INT','INF','VE','NVSE']])
model1 = sm.OLS(df['AL'], X1).fit()
print(f"\nRegression 1: R² = {model1.rsquared:.4f}")
print(model1.summary())

# Regression 2
X2 = sm.add_constant(df[['TRUST','CONV','ENJ','SC']])
model2 = sm.OLS(df['AL'], X2).fit()
print(f"\nRegression 2: R² = {model2.rsquared:.4f}")
print(model2.summary())

print("\n" + "="*80)
print("✅ HOÀN THÀNH!")
print("="*80)

# ============================================================
# BỔ SUNG: TÍNH GIÁ TRỊ MIN CỦA TỪNG THANG ĐO
# ============================================================
import pandas as pd
import numpy as np

df = pd.read_csv("onlinebuy.csv")

scale_min = df[likert_vars].min()
print(scale_min)

# ============================================================
# 2. CRONBACH'S ALPHA
# ============================================================

def cronbach_alpha(df_scale):
    k = df_scale.shape[1]
    item_var = df_scale.var(axis=0, ddof=1)
    total_var = df_scale.sum(axis=1).var(ddof=1)
    return (k/(k-1))*(1 - item_var.sum()/total_var)

scales = {
    'Interactivity': ['int1','int2'],
    'Informativeness': ['inf1','inf2','inf3'],
    'Visual_Engagement': ['ve1','ve2','ve3'],
    'Navigation_Ease': ['nvse1','nvse2'],
    'Trust': ['trust1','trust2','trust3'],
    'Convenience': ['conv1','conv2','conv3','conv4'],
    'Enjoyment': ['enj1','enj2','enj3'],
    'Self_Control': ['sc1','sc2'],
    'Attitudinal_Loyalty': ['al1','al2','al3']
}

print("\n=== CRONBACH'S ALPHA THEO TỪNG THANG ĐO ===")
for name, cols in scales.items():
    alpha = cronbach_alpha(df[cols])
    print(f"{name}: {alpha:.3f}")

# ============================================================
# 3. EXPLORATORY FACTOR ANALYSIS (EFA)
# ============================================================
!pip install factor_analyzer

from factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity, calculate_kmo

efa_data = df[likert_vars].dropna()

# Bartlett test & KMO
chi_square, p_value = calculate_bartlett_sphericity(efa_data)
kmo_all, kmo_model = calculate_kmo(efa_data)

print("Bartlett Test p-value:", p_value)
print("KMO:", kmo_model)

# Eigenvalues
fa_ev = FactorAnalyzer(rotation=None)
fa_ev.fit(efa_data)
ev, v = fa_ev.get_eigenvalues()

print("\nEigenvalues:")
print(ev)

# Số nhân tố = số eigenvalue > 1
n_factors = sum(ev > 1)
print("\nSố nhân tố được đề xuất:", n_factors)

# EFA với Varimax
fa = FactorAnalyzer(n_factors=n_factors, rotation="varimax")
fa.fit(efa_data)

loadings = pd.DataFrame(fa.loadings_, index=likert_vars)
print("\nFactor Loadings:")
loadings

# ============================================================
# 4. PEARSON CORRELATION
# ============================================================

# Import thư viện
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns   # dùng heatmap trực quan

# Tính ma trận tương quan
corr = df[likert_vars].corr()

# Hiển thị bảng tương quan
corr

# ============================================================
# 4.1. CORRELATION HEATMAP - Trực quan hóa ma trận tương quan
# ============================================================

# Tạo heatmap cho ma trận tương quan
plt.figure(figsize=(16, 14))
sns.heatmap(
    corr,
    annot=True,      # Hiển thị giá trị số
    fmt='.2f',       # Format 2 chữ số thập phân
    cmap='coolwarm', # Màu sắc: đỏ = tương quan dương, xanh = tương quan âm
    center=0,        # Trung tâm tại 0
    square=True,     # Ô vuông
    linewidths=0.5,  # Đường chia
    cbar_kws={"shrink": 0.8}
)
plt.title('Ma trận tương quan Pearson giữa các biến', fontsize=16, pad=20)
plt.tight_layout()
plt.show()

print("\n📊 Giải thích:")
print("- Màu đỏ đậm: Tương quan dương mạnh (gần +1)")
print("- Màu xanh đậm: Tương quan âm mạnh (gần -1)")
print("- Màu trắng: Không có tương quan (gần 0)")

# ============================================================
# 5. K-MEANS CLUSTERING
# ============================================================
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Tạo điểm trung bình cho từng thang đo
df['INT'] = df[['int1','int2']].mean(axis=1)
df['INF'] = df[['inf1','inf2','inf3']].mean(axis=1)
df['VE'] = df[['ve1','ve2','ve3']].mean(axis=1)
df['NVSE'] = df[['nvse1','nvse2']].mean(axis=1)
df['TRUST'] = df[['trust1','trust2','trust3']].mean(axis=1)
df['CONV'] = df[['conv1','conv2','conv3','conv4']].mean(axis=1)
df['ENJ'] = df[['enj1','enj2','enj3']].mean(axis=1)
df['SC'] = df[['sc1','sc2']].mean(axis=1)

cluster_vars = ['INT','INF','VE','NVSE','TRUST','CONV','ENJ','SC']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[cluster_vars])

k = 3  # có thể đổi 2/3/4 cụm
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(X_scaled)

print("Số lượng trong từng cụm:")
print(df['cluster'].value_counts())

print("\nTrung bình đặc tính từng cụm:")
df.groupby('cluster')[cluster_vars].mean().round(3)

# ============================================================
# 5.1. ĐẶT TÊN CHO CÁC CLUSTER
# ============================================================

# Xem lại đặc điểm trung bình của từng cluster
cluster_stats = df.groupby('cluster')[cluster_vars].mean().round(3)
print("Đặc điểm trung bình của từng cluster:")
display(cluster_stats)

# Phân tích để đặt tên cluster
print("\n" + "="*70)
print("PHÂN TÍCH ĐẶC ĐIỂM CỤM:")
print("="*70)

# Cluster 0: Purchase Intention, Trust, Convenience, Enjoyment cao
print("\n🎯 Cluster 0: 'Enthusiastic Shoppers' (Người mua sắm nhiệt tình)")
print("   - Đặc điểm: INT cao (4.594), TRUST cao (3.396), CONV cao (4.152), ENJ cao (4.080)")
print("   - VE trung bình (2.446), NVSE thấp (1.827)")
print("   - Ý nghĩa: Nhóm có ý định mua cao, tin tưởng và thích thú với mua sắm online")

# Cluster 1: Tất cả chỉ số thấp nhất
print("\n😟 Cluster 1: 'Skeptical Browsers' (Người duyệt web nghi ngờ)")
print("   - Đặc điểm: INT thấp nhất (3.114), TRUST thấp nhất (2.871), CONV thấp nhất (3.393)")
print("   - VE cao nhất (2.569), NVSE cao nhất (2.979)")
print("   - Ý nghĩa: Nhóm ít tin tưởng, ít ý định mua, lo lắng về rủi ro và tự đánh giá tiêu cực")

# Cluster 2: INT cao nhất, VE thấp nhất, các chỉ số dương tính cao nhất
print("\n⭐ Cluster 2: 'Convenience Seekers' (Người tìm kiếm sự tiện lợi)")
print("   - Đặc điểm: INT cao nhất (4.641), CONV cao nhất (4.766), ENJ cao nhất (4.970)")
print("   - TRUST cao nhất (4.308), VE thấp nhất (1.624), NVSE thấp nhất (1.468)")
print("   - Ý nghĩa: Nhóm hoàn hảo - tin tưởng cao, rủi ro thấp, yêu thích sự tiện lợi")

# Tạo dictionary mapping cluster number sang tên
cluster_names = {
    0: 'Enthusiastic Shoppers',
    1: 'Skeptical Browsers',
    2: 'Convenience Seekers'
}

# Thêm cột tên cluster vào dataframe
df['cluster_name'] = df['cluster'].map(cluster_names)

# Hiển thị phân bố
print("\n" + "="*70)
print("PHÂN BỐ SỐ LƯỢNG KHÁCH HÀNG THEO CỤM:")
print("="*70)
cluster_distribution = df.groupby(['cluster', 'cluster_name']).size().reset_index(name='Số lượng')
cluster_distribution['Tỷ lệ (%)'] = (cluster_distribution['Số lượng'] / len(df) * 100).round(2)
display(cluster_distribution)

# Tạo visualization cho cluster names
plt.figure(figsize=(10, 6))
counts = df['cluster_name'].value_counts()
colors = ['#2ecc71', '#e74c3c', '#3498db']  # Màu cho mỗi cluster
plt.bar(counts.index, counts.values, color=colors, edgecolor='black', linewidth=1.5)
plt.xlabel('Tên Cluster', fontsize=12, fontweight='bold')
plt.ylabel('Số lượng khách hàng', fontsize=12, fontweight='bold')
plt.title('Phân bố khách hàng theo các nhóm', fontsize=14, fontweight='bold')
plt.xticks(rotation=15, ha='right')

# Thêm số lượng trên mỗi cột
for i, (name, value) in enumerate(counts.items()):
    plt.text(i, value + 2, str(value), ha='center', fontweight='bold', fontsize=11)

plt.tight_layout()
plt.show()

print("\n✅ Đã hoàn thành việc đặt tên các cluster!")
print("Cột 'cluster_name' đã được thêm vào dataframe.")

# ============================================================
# 5.2. MARKETING INSIGHTS & RECOMMENDATIONS
# ============================================================

print("="*80)
print("🎯 CHIẾN LƯỢC MARKETING CHO TỪNG NHÓM KHÁCH HÀNG")
print("="*80)

print("\n" + "-"*80)
print("📊 CLUSTER 0: 'ENTHUSIASTIC SHOPPERS' (Người mua sắm nhiệt tình)")
print(f"   Số lượng: {len(df[df['cluster']==0])} khách hàng ({len(df[df['cluster']==0])/len(df)*100:.1f}%)")
print("-"*80)
print("💡 Chiến lược:")
print("   • Loyalty Programs: Tạo chương trình khách hàng thân thiết với ưu đãi đặc biệt")
print("   • Premium Services: Cung cấp dịch vụ giao hàng nhanh, free shipping")
print("   • Exclusive Offers: Gửi ưu đãi độc quyền, flash sale sớm nhất")
print("   • Social Proof: Thu thập review tích cực từ nhóm này")
print("   • Upselling/Cross-selling: Giới thiệu sản phẩm cao cấp hơn")

print("\n" + "-"*80)
print("📊 CLUSTER 1: 'SKEPTICAL BROWSERS' (Người duyệt web nghi ngờ)")
print(f"   Số lượng: {len(df[df['cluster']==1])} khách hàng ({len(df[df['cluster']==1])/len(df)*100:.1f}%)")
print("-"*80)
print("💡 Chiến lược:")
print("   • Trust Building: Hiển thị chứng chỉ bảo mật, đảm bảo hoàn tiền")
print("   • Risk Reduction: Chính sách đổi trả linh hoạt, dùng thử miễn phí")
print("   • Social Proof: Hiển thị review, rating, số người đã mua")
print("   • First Purchase Incentives: Giảm giá lần đầu, freeship đơn đầu")
print("   • Education: Hướng dẫn chi tiết về sản phẩm, FAQ đầy đủ")
print("   • Customer Support: Hỗ trợ 24/7, chatbot thông minh")

print("\n" + "-"*80)
print("📊 CLUSTER 2: 'CONVENIENCE SEEKERS' (Người tìm kiếm sự tiện lợi)")
print(f"   Số lượng: {len(df[df['cluster']==2])} khách hàng ({len(df[df['cluster']==2])/len(df)*100:.1f}%)")
print("-"*80)
print("💡 Chiến lược:")
print("   • Convenience Features: 1-click checkout, lưu thông tin thanh toán")
print("   • Fast Delivery: Giao hàng trong ngày, express delivery")
print("   • Mobile Optimization: App mobile mượt mà, thân thiện")
print("   • Subscription Model: Đăng ký nhận hàng định kỳ (auto-replenish)")
print("   • Personalization: Gợi ý sản phẩm dựa trên lịch sử mua")
print("   • Premium Experience: VIP support, dedicated account manager")

print("\n" + "="*80)
print("✅ KẾT LUẬN TỔNG QUAN")
print("="*80)
print("""
• Cluster 2 (Convenience Seekers): Nhóm VIP - Đầu tư mạnh nhất
• Cluster 0 (Enthusiastic Shoppers): Nhóm tiềm năng - Duy trì & phát triển
• Cluster 1 (Skeptical Browsers): Nhóm cần chuyển đổi - Tập trung xây dựng lòng tin

🎯 Ưu tiên:
1. Giữ chân và phát triển Cluster 2 (Revenue cao nhất)
2. Nâng cấp Cluster 0 lên Cluster 2
3. Chuyển đổi Cluster 1 thành khách hàng trung thành
""")
print("="*80)

# ============================================================
# KMEANS — VẼ CÁC CỤM BẰNG PCA 2D
# ============================================================
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)
pca_result = pca.fit_transform(X_scaled)

df['pca1'] = pca_result[:, 0]
df['pca2'] = pca_result[:, 1]

plt.figure(figsize=(8,6))
for c in range(k):
    plt.scatter(
        df[df['cluster'] == c]['pca1'],
        df[df['cluster'] == c]['pca2'],
        label=f'Cụm {c}',
        alpha=0.7
    )
plt.title("Biểu đồ PCA — Phân cụm K-Means")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.legend()
plt.show()

# ============================================================
# SCATTER 2 BIẾN (TRUST – ENJOYMENT)
# ============================================================

plt.figure(figsize=(8,6))
for c in range(k):
    plt.scatter(
        df[df['cluster']==c]['TRUST'],
        df[df['cluster']==c]['ENJ'],
        label=f'Cụm {c}',
        alpha=0.7
    )
plt.title("Scatter Plot: TRUST vs ENJ theo từng cụm")
plt.xlabel("TRUST")
plt.ylabel("ENJOYMENT")
plt.legend()
plt.show()

# ============================================================
# VẼ RADAR CHART CHO TRUNG BÌNH CÁC THANG ĐO
# ============================================================
import numpy as np

cluster_mean = df.groupby('cluster')[cluster_vars].mean()

labels = cluster_vars
num_vars = len(labels)

angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]

plt.figure(figsize=(10,8))

for i, row in cluster_mean.iterrows():
    values = row.tolist()
    values += values[:1]
    plt.polar(angles, values, marker='o', label=f'Cụm {i}')

plt.title("Radar Chart — Đặc điểm trung bình các cụm")
plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1.1))
plt.show()

# ============================================================
# SILHOUETTE SCORE — ĐÁNH GIÁ CHẤT LƯỢNG PHÂN CỤM
# ============================================================
from sklearn.metrics import silhouette_score

score = silhouette_score(X_scaled, df['cluster'])
print("Silhouette Score =", score)

# ============================================================
# SILHOUETTE PLOT
# ============================================================
from sklearn.metrics import silhouette_samples
import matplotlib.cm as cm

silhouette_vals = silhouette_samples(X_scaled, df['cluster'])

plt.figure(figsize=(8,6))
y_lower = 10

for i in range(k):
    ith_cluster_silhouette = silhouette_vals[df['cluster'] == i]
    ith_cluster_silhouette.sort()

    size_cluster_i = ith_cluster_silhouette.shape[0]
    y_upper = y_lower + size_cluster_i

    color = cm.nipy_spectral(float(i) / k)
    plt.fill_betweenx(
        np.arange(y_lower, y_upper),
        0,
        ith_cluster_silhouette,
        facecolor=color,
        alpha=0.7
    )
    plt.text(-0.05, y_lower + 0.5 * size_cluster_i, str(i))
    y_lower = y_upper + 10

plt.axvline(score, color="red", linestyle="--")
plt.title("Silhouette Plot cho K-Means")
plt.xlabel("Silhouette Coefficient")
plt.ylabel("Cluster")
plt.show()

# ============================================================
# 6. MULTIPLE REGRESSION predicting AL
# ============================================================
import statsmodels.api as sm

df['AL'] = df[['al1','al2','al3']].mean(axis=1)

# Platform Features → AL
X1 = df[['INT','INF','VE','NVSE']]
y1 = df['AL']
X1 = sm.add_constant(X1)

model1 = sm.OLS(y1, X1).fit()
print(model1.summary())

# ============================================================
# 7. LOGISTIC REGRESSION predicting target
# ============================================================
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X2 = df[['TRUST','CONV','ENJ','SC']]
y2 = df['target']

logit = LogisticRegression(max_iter=1000)
logit.fit(X2, y2)

y_pred = logit.predict(X2)
print(classification_report(y2, y_pred))

from sklearn.neural_network import MLPClassifier

ann = MLPClassifier(hidden_layer_sizes=(8,4), activation='relu', solver='adam',
                    max_iter=1000, random_state=42)

ann.fit(X2, y2)
y_pred_ann = ann.predict(X2)

print("\nKết quả ANN:")
print(classification_report(y2, y_pred_ann))

